# Solar Expanse Build Cost Calculator
# ====================================

PYTHON     := python

# GAME_DIR: path to Solar Expanse install.
# Override via env var SOLAR_EXPANSE_DIR or pass as make variable.
GAME_DIR   ?= $(or $(SOLAR_EXPANSE_DIR),)

# Guard: fail early with a clear message when GAME_DIR is required but not set.
# Use as the first line of a recipe:  $(call require-game-dir)
require-game-dir = $(if $(strip $(GAME_DIR)),,$(error GAME_DIR is not set. Set GAME_DIR=... or set SOLAR_EXPANSE_DIR env var.))

DATA_DIR   := data
ICONS_DIR  := icons

# --- Intermediate outputs (generated by BepInEx plugin) ---
FACILITY_JSON   := $(DATA_DIR)/facility_costs.json
SPACECRAFT_JSON := $(DATA_DIR)/spacecraft_costs.json
LAUNCH_VEHICLE_JSON := $(DATA_DIR)/launch_vehicle_costs.json
LOC_NAMES_TXT   := $(DATA_DIR)/loc_names.txt
BUILDABILITY_JSON := $(DATA_DIR)/extracted_buildability.json
RESEARCH_JSON     := $(DATA_DIR)/research_unlocks.json

# --- Final output ---
HTML_OUT := index.html

.PHONY: all clean icons table help extract-run

# --- Default target: full pipeline ---
all: extract-run icons table

help:
	@echo "Solar Expanse Build Cost Calculator"
	@echo ""
	@echo "  extract-run  Build plugin, launch game, extract all data -> data/*"
	@echo "  icons        Extract resource icons from game assets -> icons/"
	@echo "  table        Generate HTML calculator -> index.html"
	@echo "  all          Full pipeline: extract-run + icons + table"
	@echo "  clean        Remove all generated files"
	@echo ""
	@echo "Typical workflow:"
	@echo "  make extract-run icons table"
	@echo ""
	@echo "Variables:"
	@echo "  GAME_DIR            Path to Solar Expanse install"
	@echo "  SOLAR_EXPANSE_DIR   Env var alternative to GAME_DIR"

# --- BepInEx plugin: build, deploy, run game, extract, kill ---
extract-run:
	$(call require-game-dir)
	$(PYTHON) run_extract.py --game-dir "$(GAME_DIR)"

# --- Resource icons (Python, reads game assets) ---
# Uses a stamp file to avoid cyclic dependency (icons dir = target name)
ICONS_STAMP := $(ICONS_DIR)/.stamp

$(ICONS_STAMP): extract_icons.py
	$(call require-game-dir)
	@echo "[*] Extracting resource icons..."
	$(PYTHON) extract_icons.py --game-dir "$(GAME_DIR)"
	@touch "$(ICONS_STAMP)"

icons: $(ICONS_STAMP)

# --- Data files (generated by BepInEx plugin) ---
# Fail with a helpful error when game-extracted data files are missing.
# These files can only be created by 'make extract-run', not by a static rule.
$(FACILITY_JSON) $(SPACECRAFT_JSON) $(LAUNCH_VEHICLE_JSON) $(LOC_NAMES_TXT) $(BUILDABILITY_JSON) $(RESEARCH_JSON):
	@echo "ERROR: Game data files not found in $(DATA_DIR)/." >&2
	@echo "Run 'make extract-run' first." >&2
	@exit 1

# --- HTML table ---
$(HTML_OUT): generate_table.py $(FACILITY_JSON) $(SPACECRAFT_JSON) $(LAUNCH_VEHICLE_JSON) $(ICONS_STAMP) $(LOC_NAMES_TXT) $(BUILDABILITY_JSON) $(RESEARCH_JSON)
	@echo "[*] Generating HTML build cost calculator..."
	$(PYTHON) generate_table.py

table: $(HTML_OUT)

# --- Clean ---
clean:
	@echo "[*] Cleaning generated files..."
	-@rm -rf "$(DATA_DIR)"
	-@rm -rf "$(ICONS_DIR)"
	-@rm -f "$(HTML_OUT)"
	-@rm -rf extract/bin extract/obj
